/* -------------------------------------------------------------------------- */
/*                                  REGISTER                                  */
/* -------------------------------------------------------------------------- */

export interface RegisterPayload {
  userName: string;
  password: string;
  email: string;
  name: string;
  mobile: string;
}

export type RegisterErrorResponse = {
  ok: boolean;
  message: string;
  errors: RegisterError[];
};

/* -------------------------------------------------------------------------- */
/*                               REGISTER ERROR                               */
/* -------------------------------------------------------------------------- */

export type RegisterError = {
  status: number;
};
// Generated by https://quicktype.io

export interface RegisterResponse {
  success: null;
  message: string;
  data: null;
  metadata: null;
  status: number;
  action: null;
  signature: null;
  type: string;
  id: null;
  ok: boolean;
}
